### ISSUE TITLE
Add HackerNews example

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/gotk4-examples#10]
It might be a good idea to go all out and write a non-trivial example application using this library. Hopefully, it'll teach people a wide range of best practices from concurrency to project organization.

One such non-trivial idea is a read-only HackerNews application with comments.

**Comment by khrome83** [comment]
I would love that. 

I know when I reach outside the examples, it's really hard to find examples. 

I have had some luck looking at GTK4 docs, but very limited. For example, I can't make sense of making an editable `gtx.TextView` right now. Even when I try to use the C docs and translate to Go, I am messing something up. 

So far though, I am loving this. The CSS example was a wonderful help.
