### ISSUE TITLE
adwaita example

### ISSUE THREAD

**Issue by dada513** [diamondburned/gotk4-examples#13]
would be nice to have an example to use libadwaita

**Comment by diamondburned** [comment]
https://github.com/diamondburned/gotk4-adwaita/blob/adw/pkg/_examples/flap/main.go

**Comment by dada513** [comment]
> https://github.com/diamondburned/gotk4-adwaita/blob/adw/pkg/_examples/flap/main.go

Thanks you should link it in readme of gotk4 adwaita
