### ISSUE TITLE
Add a Builder GTK4 example (importing a UI)

### ISSUE THREAD

**Issue by erazemk** [diamondburned/gotk4-examples#16]
I've only found a few Go GTK3 tutorials for importing UI files using Builder, but I haven't found any that do it for GTK4.
Since the syntax has changed a lot the old code doesn't work, so having an example would be very useful.

For reference this is where I get stuck:
```go
builder := gtk.NewBuilderFromFile("myfile.ui")
button := builder.GetObject("button")
```

`GetObject` returns an object as expected, but in GTK3 you could type convert it into a `gtk.Button` by appending `.(*gtk.Button)`, which doesn't work with GTK4 (error `Invalid type assertion: builder.GetObject("Button").(*gtk.Button) (non-interface type *externglib.Object on the left)`).

**Comment by diamondburned** [comment]
You'll need to explicitly call Cast:

```go
button := builder.GetObject("button").Cast().(*gtk.Button)
```

This is less of a GTK4 change and more of a "the GTK schema has always had this and the autogenerator is not smart enough to know better."

**Comment by diamondburned** [comment]
As a side-note, feel free to PR in a new GTK4 example that demos this. I recommend using the `go:embed` API, too:

```
- ui/
  - view.xml
- main.go
```

```go
//go:embed ui
var uiFiles embed.FS

// use uiFiles...
```

**Comment by erazemk** [comment]
Thanks :)
