### ISSUE TITLE
Rebuild to account for gotk4 commit dd5e83c

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/gotk4-examples#3]
Commit dd5e83c is breaking. Rebuild the examples to see if they still work.

**Comment by erazemk** [comment]
Can confirm they do not work.

Returned error is:
```sh
# github.com/diamondburned/gotk4/pkg/core/intern
/home/<username>/.local/share/golang/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.0.0-20211219001913-8429c7410c60/core/intern/intern.go:114:9: no new variables on left side of :=
```

**Comment by diamondburned** [comment]
This was a careless mistake that I made yesterday. I fixed it upstream and bumped the version in this repository.

Closing this issue since it's fixed.
