### ISSUE TITLE
assume-no-moving-gc warning on simple example

### ISSUE THREAD

**Issue by william-lohan** [diamondburned/gotk4-examples#34]
With this example https://github.com/diamondburned/gotk4-examples/blob/master/gtk4/simple/main.go I get the following error:

> panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.21 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH="go1.21" set. Notably, if go1.21 adds a moving garbage collector, this program is unsafe to use.

How do I try out gotk4 without "risking it"?

**Comment by diamondburned** [comment]
Sorry, a version bump of this dependency in gotk4-examples is probably needed.

**Comment by william-lohan** [comment]
How do I do that? Sorry I'm also new to Go. It looks like the dependencies are just github links to the main gotk repo

https://github.com/diamondburned/gotk4-examples/blob/2b6b92a2057fa1021fd979e60ff0bd14937d8c6a/gtk4/simple/main.go#L6-L7

**Comment by diamondburned** [comment]
All good, I can update it. It's just running `go get go4.org/unsafe/assume-no-moving-gc@latest`.
